# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Do not build on tags (GitHub only)
skip_tags: true

# avoid malicious attempt via pull requests
branches:
  only:
    - master


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: http://www.appveyor.com/docs/installed-software
os: Visual Studio 2015

environment:
  REPO_DIR: &REPO_DIR c:\project  # directory created by appveyor

  OGG_SOL_FILE: libogg_static.sln
  OGG_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=Win32
  OGG_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64

  OPUS_SOL_FILE: opus.sln
  OPUS_GIT_TAG: v1.1.2
  OPUS_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=Win32 /t:celt;opus;silk_common;silk_float
  OPUS_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64   /t:celt;opus;silk_common;silk_float

  OPUS-TOOLS_SOL_FILE: opus-tools.sln
  OPUS-TOOLS_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=Win32
  OPUS-TOOLS_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64

# clone directory
clone_folder: *REPO_DIR


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  # git submodules
  - 'cd "%REPO_DIR%"'
  - 'git submodule update --init --remote --recursive'

  # prepare ogg
  - 'cd "%REPO_DIR%"'
  - 'rd /S /Q "lib\libogg\win32\VS2015"'
  - 'move /Y "src\ogg\VS2015" "lib\libogg\win32"'
  - 'msbuild "lib\libogg\win32\VS2015\%OGG_SOL_FILE%" %OGG_MSBUILD_CMD_X86%'
  - 'msbuild "lib\libogg\win32\VS2015\%OGG_SOL_FILE%" %OGG_MSBUILD_CMD_X64%'

  # prepare opus
  - 'cd "%REPO_DIR%\lib\opus"'
  - 'git checkout tags/%OPUS_GIT_TAG%'
  - 'cd "%REPO_DIR%"'
  - 'rd /S /Q "lib\opus\win32\VS2015"'
  - 'move /Y "src\opus\VS2015" "lib\opus\win32"'
  - 'msbuild "lib\opus\win32\VS2015\%OPUS_SOL_FILE%" %OPUS_MSBUILD_CMD_X86%'
  - 'msbuild "lib\opus\win32\VS2015\%OPUS_SOL_FILE%" %OPUS_MSBUILD_CMD_X64%'

# to run your custom scripts instead of automatic MSBuild
build_script:
  - 'cd "%REPO_DIR%"'
  - 'xcopy /E /Y "src\opus-tools" "lib\opus-tools"'
  - 'msbuild "lib\opus-tools\%OPUS-TOOLS_SOL_FILE%" %OPUS-TOOLS_MSBUILD_CMD_X86%'
  - 'msbuild "lib\opus-tools\%OPUS-TOOLS_SOL_FILE%" %OPUS-TOOLS_MSBUILD_CMD_X64%'

# scripts to run before deployment
after_build:
  # prepare for artifacts packaging
  - 'cd "%REPO_DIR%"'
  - 'mkdir "win32" "x64"'
  - 'copy "lib\opus-tools\Release\opus*.exe" "win32"'
  - 'copy "lib\opus-tools\x64\Release\opus*.exe" "x64"'
  - '7z a -mx9 "opus-tools.7z" "Readme.md" "win32" "x64"'  # the artifact must reside at the source repo root
  - 'powershell -Command "& { (Get-FileHash -Algorithm SHA1 "opus-tools.7z").hash; }" > "opus-tools.7z.sha1"'


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: opus-tools.7z
    name: exe
  - path: opus-tools.7z.sha1
    name: checksum
